FROM docker.io/emscripten/emsdk:latest

# Install build dependencies
RUN apt-get update && apt-get install -y \
    cmake \
    git \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Set working directory in the container
WORKDIR /game

# Copy source code
COPY CMakeLists.txt   .
COPY src              ./src
