FROM docker.io/emscripten/emsdk:latest

# Install build dependencies
RUN apt-get update && apt-get install -y \
    cmake \
    git \
    build-essential \
    clang-format \
    && rm -rf /var/lib/apt/lists/*
