#############
# Build stage
FROM docker.io/emscripten/emsdk:latest AS builder

# Install build dependencies
RUN apt-get update && apt-get install -y \
    cmake \
    git \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Set working directory in the container
WORKDIR /game

# Copy source code
COPY CMakeLists.txt   .
COPY src              ./src

# Run CMake build
RUN emcmake cmake -S . -B build && cd build && emmake make

###############
# Hosting stage
FROM docker.io/nginx:alpine

# Copy built artifacts from builder stage
COPY --from=builder /game/build /usr/share/nginx/html

# Copy web artifacts
COPY web    /usr/share/nginx/html
COPY assets /usr/share/nginx/html/assets

# Copy Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
